server:
  port: 8080 # 내장 톰캣 포트번호

spring:
  # Database 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: 'jdbc:h2:mem:test'  # H2 DB 연결 주소 (In-Memory Mode) H2때에는 (Embedded Mode)
    url: jdbc:mysql://localhost:3306/study_db
    username: root      # H2 DB 접속 ID (사용자 지정)
    password: lhj031024 # H2 DB 접속 PW (사용자 지정)

  # H2 Console 설정
  #h2:
    #console: # H2 DB를 웹에서 관리할 수 있는 기능
      #enabled: true           # H2 Console 사용 여부
      #path: /h2-console       # H2 Console 접속 주소

  # JPA 설정
  jpa:
    #database-platform: org.hibernate.dialect.Dialect #H2Dialect
    hibernate:
      ddl-auto: update       # DB 초기화 전략 (none, create, create-drop, update, validate)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true      # 쿼리 로그 포맷 (정렬)
        show_sql: true        # 쿼리 로그 출력